Move legality
chessworld/TorneloScoresheet pull request #139
Opened 2022-09-14 12:00 UTC by gwenllian1

- Only legal moves can now be made
- Created 'legality' structure for moves to indicate why they are illegal
- Updated tests that failed because the moves were illegal
- Wrote tests for move legality

Kat + Llio.

2022-09-17 04:14 UTC, nocommentcode requested changes
Great stuff guys, 
A few of my comments are irrelevant because the commiting is kind of all over the place so ignor the comments that you already addressed.
A few other things:
- In chess engine's generate pgn function, we are still calling chess.forceMove
- in the chess engine tests, for some reason the tests are still passing but they should be failing... Since we are not allowing illegal moves anymore, the illegal  move tests should be failing but they are not, i dont understand why

2022-09-17 04:15 UTC, nocommentcode commented on packages/TorneloScoresheet/src/hooks/appMode/recordingState.ts
> +        console.log(appModeState.pairing.positionOccurances);
i think this was fixed in a later commit

2022-09-17 04:15 UTC, nocommentcode commented on packages/TorneloScoresheet/src/hooks/appMode/recordingState.ts
> +    const [, showError] = useError();
i think this was fixed in a later commit

2022-09-17 04:17 UTC, nocommentcode commented on packages/TorneloScoresheet/src/hooks/appMode/recordingState.ts
> +      return;
just to be clear, this function should just take in a fen and return a moveLegality object, and in processPlayerMove, when we instanciate the next ply, we will have moveLegality:checkMoveLegality(nexFen)

2022-09-17 04:21 UTC, nocommentcode commented
Also if we are in 5 fold repetition, how is the arbiter mode supposed to detect this? Since we arent setting the 5 fold repetition legality check to true in all 5 plys in the code (unless i missed it)?

2022-09-17 05:24 UTC, gwenllian1 commented on packages/TorneloScoresheet/src/pages/GraphicalRecording/PromotionSheet.tsx
> -    { icon: PAWN, onPress: () => handleSelectPromotion(PieceType.Pawn) },
<img width="656" alt="image" src="https://user-images.githubusercontent.com/64511606/190841900-c5098739-85a0-401b-a978-99083c580bcd.png">
we googled it and the general vibe was that you had to promote a pawn

2022-09-17 05:33 UTC, gwenllian1 commented on packages/TorneloScoresheet/src/hooks/appMode/recordingState.ts
> +      }
If we don't include the check then players can add skips when the game is already in fivefold repetition which they shouldn't be allowed to do.

2022-09-17 07:57 UTC, nocommentcode commented on packages/TorneloScoresheet/src/pages/GraphicalRecording/PromotionSheet.tsx
> -    { icon: PAWN, onPress: () => handleSelectPromotion(PieceType.Pawn) },
oh true ignore me then

2022-09-17 08:02 UTC, nocommentcode requested changes
good stuff i found the problem with the tests, 
we need:
`expect(nextFenResult !== null).toBe(true);` on lines 1024 and 1055, this is required to make sure the engine is not returning null on a possible move. This will break the tests so you can fix the test cases that should not be passing

2022-09-17 11:50 UTC, nocommentcode approved these changes
Perfect gg!

2022-09-17 13:39 UTC, ksov0001 approved these changes
Approving again after fixing package lock for CI

2022-09-18 02:08 UTC, ksov0001 approved these changes
Triggering CI again

2022-09-18 02:21 UTC, nocommentcode approved these changes
fixing ci issue

2022-09-18 03:49 UTC, nocommentcode commented
Closed as I am refractoring some sections of this pr

2022-09-18 03:49 UTC, closed without merging