Editing add skips
chessworld/TorneloScoresheet pull request #143
Opened 2022-09-18 10:32 UTC by gwenllian1

If a move is edited, all future moves that are made illegal are replaced with skips
Kat + Llio.

https://user-images.githubusercontent.com/64511606/190897721-dab5e10d-c5a7-4138-af3c-c5c0c2d959be.mp4

2022-09-19 02:45 UTC, nocommentcode requested changes
Looks good, just needs a minor fix with the legality checking.
I also realised there was a bug with the previous version, I was checking the legality with the previous fen instead of the next fen for skip plys, so this needs to be changed!

2022-09-19 02:45 UTC, nocommentcode commented on packages/TorneloScoresheet/src/hooks/appMode/editMoveState.ts
> +        type: PlyTypes.SkipPly,
Missing the legality check here, it should be performed with the fen after this skip ply is recorded

2022-09-19 02:45 UTC, nocommentcode commented on packages/TorneloScoresheet/src/hooks/appMode/editMoveState.ts
> +      return previousPly;
Also we need to update the posistion occureneces with this new fen before returning previous ply

2022-09-19 02:45 UTC, nocommentcode commented on packages/TorneloScoresheet/src/hooks/appMode/editMoveState.ts
> +          legality: checkMoveLegality(previousStartingFen, positionOccurances),
The legality of this move needs to be checked with the fen resulting from this move, ie you need `const nextFen = chessEngine.skipTurn(previousStartingFen)` before declaring previousPly, then you need to call checkMoveLegality with this next fen,
 I just noticed there is a bug in the previous version, in line 138, it should be checking the legality with the next fen too!

2022-09-19 02:45 UTC, nocommentcode commented on packages/TorneloScoresheet/src/hooks/appMode/editMoveState.ts
> +      return previousPly;
and then we need to set the previous starting fen to be this new fen

2022-09-22 00:23 UTC, nocommentcode approved these changes
nicely done :)

2022-09-22 00:38 UTC, nocommentcode approved these changes
!

2022-09-22 01:07 UTC, ksov0001 approved these changes
Re-approving after rebase

2022-09-22 01:12 UTC, merged