Standardise Arbiter Mode navigation
chessworld/TorneloScoresheet pull request #166
Opened 2022-10-16 04:20 UTC by nocommentcode

This PR standardises the way the arbiter will navigation between app modes.
Previously some arbiter modes had a button to select which mode to return to, some arbiter modes had a back button, and some arbiter modes used a back button in the toolbar.
This PR makes it so all arbiter modes use a hamburger menu icon in the toolbar to select which mode to go to.
This opens an option sheet that the arbiter can use to select which app mode they want to move to 

https://user-images.githubusercontent.com/26475724/196017736-44c6290c-7cec-4d6b-bb1d-b292b47b59de.mp4

2022-10-16 05:57 UTC, gwenllian1 requested changes
I really like this, I think it's much better than what we had before.

2022-10-16 05:57 UTC, gwenllian1 commented on packages/TorneloScoresheet/src/components/Toolbar/ArbiterModeNavigation.tsx
> +    [AppMode.EnterPgn]: true,
this is under do not show arbiter navigation button but is set to true

2022-10-16 21:58 UTC, gestureleft commented
Just wanted to chime in on the design! I really like this idea, but not sure if a hamburger menu icon is the right icon to go with, since it doesn't open a hamburger menu? So I reckon we either use a different icon, or put the navigation in a hamburger menu. New icon would probably be easiest. Or we could leave it as is, and leave implementing a hamburger menu as an exercise for the reader 🤔

2022-10-17 02:16 UTC, nocommentcode commented
yep agreed, I changed it to an arrow down icon

2022-10-17 02:33 UTC, gwenllian1 approved these changes

2022-10-17 02:43 UTC, merged